### ISSUE TITLE
Haskell 中文社区第一帖

### ISSUE THREAD

**Issue by gingerhot** [hskll/community#1]
# 欢迎大家使用该 Repo 一起建立 Haskell 中文社区

**优点：**

* 无需注册，使用 GitHub 账号可以发言、回复
* 有强大的 GitHub 作为后盾，零运维，零投入，不会出现论坛消失的状况
* 使用熟悉的 GitHub 工具，尤其是 Markdown 等工具，支持直接贴图
* GitHub 的 Issue tracker 功能强大，可以使用 # 在各 issue 之间进行引用
* 可以使用关键词搜索感兴趣的话题
* 可以加各种标签增强检索功能
* 精华帖子会展示在 http://Haskell.group 的首页

**如何访问：**

* 从 [Haskell 中国用户组首页](http://haskell.group/)点击“Haskell 社区”进入
* 或者直接访问该 Discussions 页面：https://github.com/hskll/community/discussions
* 你也可以 star 本项目，每次从 Discussions 标签页点入

**如何发帖：** 在 [Issues 页面](https://github.com/hskll/community/issues)点击右侧的 `New issue` 按钮即可发帖

**使用 Wiki 沉淀内容：** 欢迎在本 Repo 的 [Wiki 页面](https://github.com/hskll/community/wiki)协同编辑感兴趣的内容

![haskell china](https://www.haskell.org/static/img/haskell-logo.svg)

**Comment by qinxij** [comment]
谢谢建设这个Haskell社区，但是Haskell中文用户太少了。

**Comment by gingerhot** [comment]
> 谢谢建设这个Haskell社区，但是Haskell中文用户太少了。

👍 社区需要大家的努力，比如：

1.  在这里发帖提问或分享自己的经历和经验
2. 在 wiki 分享 Haskell 学习资源、翻译 Haskell 文档
3. 在社交媒体分享论坛的链接
